/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const SubjectScores = IDL.Record({
  'ai' : IDL.Opt(IDL.Nat),
  'pe' : IDL.Opt(IDL.Nat),
  'evs' : IDL.Opt(IDL.Nat),
  'biology' : IDL.Opt(IDL.Nat),
  'social' : IDL.Opt(IDL.Nat),
  'hindi' : IDL.Opt(IDL.Nat),
  'math' : IDL.Opt(IDL.Nat),
  'businessStudies' : IDL.Opt(IDL.Nat),
  'computer' : IDL.Opt(IDL.Nat),
  'economics' : IDL.Opt(IDL.Nat),
  'chemistry' : IDL.Opt(IDL.Nat),
  'accountancy' : IDL.Opt(IDL.Nat),
  'physics' : IDL.Opt(IDL.Nat),
  'management' : IDL.Opt(IDL.Nat),
  'psychology' : IDL.Opt(IDL.Nat),
  'kannada' : IDL.Opt(IDL.Nat),
  'english' : IDL.Opt(IDL.Nat),
  'statistics' : IDL.Opt(IDL.Nat),
  'science' : IDL.Opt(IDL.Nat),
});
export const SaveAcademicInput = IDL.Record({
  'marks' : SubjectScores,
  'stream' : IDL.Opt(IDL.Text),
  'term' : IDL.Nat,
  'subgroup' : IDL.Opt(IDL.Text),
  'termMaxMarks' : IDL.Nat,
  'computerMaxMarks' : IDL.Nat,
  'aiMaxMarks' : IDL.Nat,
});
export const Time = IDL.Int;
export const AcademicEntry = IDL.Record({
  'totalFinalMarks' : IDL.Nat,
  'stream' : IDL.Opt(IDL.Text),
  'subjects' : SubjectScores,
  'term' : IDL.Nat,
  'gradeText' : IDL.Text,
  'overallPercentage' : IDL.Nat,
  'subgroup' : IDL.Opt(IDL.Text),
  'maxMarksPerSubject' : IDL.Nat,
  'overallMaxMarks' : IDL.Nat,
  'grade' : IDL.Nat,
  'termMaxMarks' : IDL.Nat,
  'timestamp' : Time,
  'termPercentage' : IDL.Nat,
  'computerMaxMarks' : IDL.Nat,
  'termTotalMarks' : IDL.Nat,
  'aiMaxMarks' : IDL.Nat,
});
export const CodingChallenge = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'sampleOutput' : IDL.Text,
  'description' : IDL.Text,
  'sampleInput' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BoardExamResults = IDL.Record({
  'maxMarks' : IDL.Nat,
  'boardExamTotal' : IDL.Nat,
  'percentage' : IDL.Nat,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const CodingAttempt = IDL.Record({
  'result' : IDL.Text,
  'code' : IDL.Text,
  'score' : IDL.Opt(IDL.Nat),
  'challengeId' : IDL.Nat,
  'timestamp' : Time,
});
export const GradeAggregate = IDL.Record({
  'term2Percentage' : IDL.Nat,
  'combinedOverallPercentage' : IDL.Nat,
  'term1Percentage' : IDL.Nat,
});
export const GradeAggregates = IDL.Record({
  'aggregates' : IDL.Vec(IDL.Tuple(IDL.Nat, GradeAggregate)),
});
export const AcademicEntriesExport = IDL.Record({
  'academicEntries' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(AcademicEntry))),
  'boardExamResults' : IDL.Vec(IDL.Tuple(IDL.Principal, BoardExamResults)),
});
export const CodingExport = IDL.Record({
  'attempts' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CodingAttempt))),
  'challenges' : IDL.Vec(CodingChallenge),
});
export const ExportTypes = IDL.Record({
  'academicEntries' : AcademicEntriesExport,
  'coding' : CodingExport,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addAcademicEntry' : IDL.Func(
      [IDL.Nat, IDL.Vec(SaveAcademicInput), IDL.Opt(IDL.Nat)],
      [IDL.Vec(AcademicEntry)],
      [],
    ),
  'addCodingChallenge' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [CodingChallenge],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAcademicEntries' : IDL.Func([], [IDL.Vec(AcademicEntry)], ['query']),
  'getAcademicEntriesByGrade' : IDL.Func(
      [IDL.Nat],
      [IDL.Vec(AcademicEntry)],
      ['query'],
    ),
  'getAcademicEntriesByGradeAndTerm' : IDL.Func(
      [IDL.Nat, IDL.Nat],
      [IDL.Vec(AcademicEntry)],
      ['query'],
    ),
  'getAllCodingChallenges' : IDL.Func(
      [],
      [IDL.Vec(CodingChallenge)],
      ['query'],
    ),
  'getBoardExamResults' : IDL.Func([], [BoardExamResults], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCodingAttempts' : IDL.Func([], [IDL.Vec(CodingAttempt)], ['query']),
  'getCodingChallenge' : IDL.Func([IDL.Nat], [CodingChallenge], ['query']),
  'getCombinedAcademicEntriesByGrade' : IDL.Func(
      [IDL.Nat],
      [
        IDL.Record({
          'term1' : IDL.Opt(AcademicEntry),
          'term2' : IDL.Opt(AcademicEntry),
          'combinedTotal' : IDL.Nat,
          'combinedAverage' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getGradeAggregatePercentages' : IDL.Func([], [GradeAggregates], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'importData' : IDL.Func([ExportTypes], [], []),
  'initializeAccessControl' : IDL.Func([], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'retrieveDataExportRequest' : IDL.Func([IDL.Text], [ExportTypes], ['query']),
  'saveBoardExamResults' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveCodingAttempt' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
      [CodingAttempt],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const SubjectScores = IDL.Record({
    'ai' : IDL.Opt(IDL.Nat),
    'pe' : IDL.Opt(IDL.Nat),
    'evs' : IDL.Opt(IDL.Nat),
    'biology' : IDL.Opt(IDL.Nat),
    'social' : IDL.Opt(IDL.Nat),
    'hindi' : IDL.Opt(IDL.Nat),
    'math' : IDL.Opt(IDL.Nat),
    'businessStudies' : IDL.Opt(IDL.Nat),
    'computer' : IDL.Opt(IDL.Nat),
    'economics' : IDL.Opt(IDL.Nat),
    'chemistry' : IDL.Opt(IDL.Nat),
    'accountancy' : IDL.Opt(IDL.Nat),
    'physics' : IDL.Opt(IDL.Nat),
    'management' : IDL.Opt(IDL.Nat),
    'psychology' : IDL.Opt(IDL.Nat),
    'kannada' : IDL.Opt(IDL.Nat),
    'english' : IDL.Opt(IDL.Nat),
    'statistics' : IDL.Opt(IDL.Nat),
    'science' : IDL.Opt(IDL.Nat),
  });
  const SaveAcademicInput = IDL.Record({
    'marks' : SubjectScores,
    'stream' : IDL.Opt(IDL.Text),
    'term' : IDL.Nat,
    'subgroup' : IDL.Opt(IDL.Text),
    'termMaxMarks' : IDL.Nat,
    'computerMaxMarks' : IDL.Nat,
    'aiMaxMarks' : IDL.Nat,
  });
  const Time = IDL.Int;
  const AcademicEntry = IDL.Record({
    'totalFinalMarks' : IDL.Nat,
    'stream' : IDL.Opt(IDL.Text),
    'subjects' : SubjectScores,
    'term' : IDL.Nat,
    'gradeText' : IDL.Text,
    'overallPercentage' : IDL.Nat,
    'subgroup' : IDL.Opt(IDL.Text),
    'maxMarksPerSubject' : IDL.Nat,
    'overallMaxMarks' : IDL.Nat,
    'grade' : IDL.Nat,
    'termMaxMarks' : IDL.Nat,
    'timestamp' : Time,
    'termPercentage' : IDL.Nat,
    'computerMaxMarks' : IDL.Nat,
    'termTotalMarks' : IDL.Nat,
    'aiMaxMarks' : IDL.Nat,
  });
  const CodingChallenge = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'sampleOutput' : IDL.Text,
    'description' : IDL.Text,
    'sampleInput' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BoardExamResults = IDL.Record({
    'maxMarks' : IDL.Nat,
    'boardExamTotal' : IDL.Nat,
    'percentage' : IDL.Nat,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const CodingAttempt = IDL.Record({
    'result' : IDL.Text,
    'code' : IDL.Text,
    'score' : IDL.Opt(IDL.Nat),
    'challengeId' : IDL.Nat,
    'timestamp' : Time,
  });
  const GradeAggregate = IDL.Record({
    'term2Percentage' : IDL.Nat,
    'combinedOverallPercentage' : IDL.Nat,
    'term1Percentage' : IDL.Nat,
  });
  const GradeAggregates = IDL.Record({
    'aggregates' : IDL.Vec(IDL.Tuple(IDL.Nat, GradeAggregate)),
  });
  const AcademicEntriesExport = IDL.Record({
    'academicEntries' : IDL.Vec(
      IDL.Tuple(IDL.Principal, IDL.Vec(AcademicEntry))
    ),
    'boardExamResults' : IDL.Vec(IDL.Tuple(IDL.Principal, BoardExamResults)),
  });
  const CodingExport = IDL.Record({
    'attempts' : IDL.Vec(IDL.Tuple(IDL.Principal, IDL.Vec(CodingAttempt))),
    'challenges' : IDL.Vec(CodingChallenge),
  });
  const ExportTypes = IDL.Record({
    'academicEntries' : AcademicEntriesExport,
    'coding' : CodingExport,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addAcademicEntry' : IDL.Func(
        [IDL.Nat, IDL.Vec(SaveAcademicInput), IDL.Opt(IDL.Nat)],
        [IDL.Vec(AcademicEntry)],
        [],
      ),
    'addCodingChallenge' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [CodingChallenge],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAcademicEntries' : IDL.Func([], [IDL.Vec(AcademicEntry)], ['query']),
    'getAcademicEntriesByGrade' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(AcademicEntry)],
        ['query'],
      ),
    'getAcademicEntriesByGradeAndTerm' : IDL.Func(
        [IDL.Nat, IDL.Nat],
        [IDL.Vec(AcademicEntry)],
        ['query'],
      ),
    'getAllCodingChallenges' : IDL.Func(
        [],
        [IDL.Vec(CodingChallenge)],
        ['query'],
      ),
    'getBoardExamResults' : IDL.Func([], [BoardExamResults], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCodingAttempts' : IDL.Func([], [IDL.Vec(CodingAttempt)], ['query']),
    'getCodingChallenge' : IDL.Func([IDL.Nat], [CodingChallenge], ['query']),
    'getCombinedAcademicEntriesByGrade' : IDL.Func(
        [IDL.Nat],
        [
          IDL.Record({
            'term1' : IDL.Opt(AcademicEntry),
            'term2' : IDL.Opt(AcademicEntry),
            'combinedTotal' : IDL.Nat,
            'combinedAverage' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getGradeAggregatePercentages' : IDL.Func([], [GradeAggregates], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'importData' : IDL.Func([ExportTypes], [], []),
    'initializeAccessControl' : IDL.Func([], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'retrieveDataExportRequest' : IDL.Func(
        [IDL.Text],
        [ExportTypes],
        ['query'],
      ),
    'saveBoardExamResults' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveCodingAttempt' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Opt(IDL.Nat)],
        [CodingAttempt],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };