/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicEntriesExport {
  'academicEntries' : Array<[Principal, Array<AcademicEntry>]>,
  'boardExamResults' : Array<[Principal, BoardExamResults]>,
}
export interface AcademicEntry {
  'totalFinalMarks' : bigint,
  'scienceSubgroup' : [] | [string],
  'stream' : [] | [string],
  'subjects' : Subjects,
  'term' : bigint,
  'mathsMaxMarks' : bigint,
  'gradeText' : string,
  'commerceSubgroup' : [] | [string],
  'overallPercentage' : bigint,
  'appliedMathsMaxMarks' : bigint,
  'maxMarksPerSubject' : bigint,
  'overallMaxMarks' : bigint,
  'grade' : bigint,
  'termMaxMarks' : bigint,
  'subjects9' : [] | [Score9Scale],
  'timestamp' : Time,
  'termPercentage' : bigint,
  'computerMaxMarks' : bigint,
  'termTotalMarks' : bigint,
  'aiMaxMarks' : bigint,
}
export interface AllGradesPercentages {
  'entries' : Array<[bigint, GradePercentages]>,
}
export interface BoardExamResults {
  'maxMarks' : bigint,
  'boardExamTotal' : bigint,
  'percentage' : bigint,
}
export interface CodingAttempt {
  'result' : string,
  'code' : string,
  'score' : [] | [bigint],
  'challengeId' : bigint,
  'timestamp' : Time,
}
export interface CodingChallenge {
  'id' : bigint,
  'title' : string,
  'sampleOutput' : string,
  'description' : string,
  'sampleInput' : string,
}
export interface CodingExport {
  'attempts' : Array<[Principal, Array<CodingAttempt>]>,
  'challenges' : Array<CodingChallenge>,
}
export interface CombinedPercentage {
  'overallPercentage' : bigint,
  'grade' : bigint,
}
export interface CombinedPercentages {
  'percentages' : Array<CombinedPercentage>,
}
export interface ExportTypes {
  'academicEntries' : AcademicEntriesExport,
  'coding' : CodingExport,
}
export interface GradeAggregate {
  'term2Percentage' : bigint,
  'combinedOverallPercentage' : bigint,
  'term1Percentage' : bigint,
}
export interface GradeAggregateWithWeighting {
  'term2Percentage' : bigint,
  'combinedOverallPercentage' : bigint,
  'term1Percentage' : bigint,
  'term3Percentage' : bigint,
}
export interface GradeAggregates {
  'aggregates' : Array<[bigint, GradeAggregate]>,
}
export interface GradeAggregatesWithWeighting {
  'aggregates' : Array<[bigint, GradeAggregateWithWeighting]>,
}
export interface GradePercentages {
  'term1' : [] | [bigint],
  'term2' : [] | [bigint],
  'term3' : [] | [bigint],
}
export interface SaveAcademicInput {
  'marks' : Subjects,
  'scienceSubgroup' : [] | [string],
  'stream' : [] | [string],
  'term' : bigint,
  'mathsMaxMarks' : bigint,
  'commerceSubgroup' : [] | [string],
  'appliedMathsMaxMarks' : bigint,
  'termMaxMarks' : bigint,
  'marks9' : [] | [Score9Scale],
  'computerMaxMarks' : bigint,
  'aiMaxMarks' : bigint,
}
export interface Score9Scale {
  'ai' : [] | [number],
  'pe' : [] | [number],
  'evs' : [] | [number],
  'ssc' : [] | [number],
  'maths' : [] | [number],
  'biology' : [] | [number],
  'hindi' : [] | [number],
  'math' : [] | [number],
  'businessStudies' : [] | [number],
  'computer' : [] | [number],
  'economics' : [] | [number],
  'chemistry' : [] | [number],
  'accountancy' : [] | [number],
  'physics' : [] | [number],
  'management' : [] | [number],
  'psychology' : [] | [number],
  'kannada' : [] | [number],
  'appliedMaths' : [] | [number],
  'english' : [] | [number],
  'statistics' : [] | [number],
  'science' : [] | [number],
}
export interface Subjects {
  'ai' : [] | [bigint],
  'pe' : [] | [bigint],
  'evs' : [] | [bigint],
  'ssc' : [] | [bigint],
  'maths' : [] | [bigint],
  'biology' : [] | [bigint],
  'hindi' : [] | [bigint],
  'math' : [] | [bigint],
  'businessStudies' : [] | [bigint],
  'computer' : [] | [bigint],
  'economics' : [] | [bigint],
  'chemistry' : [] | [bigint],
  'accountancy' : [] | [bigint],
  'physics' : [] | [bigint],
  'management' : [] | [bigint],
  'psychology' : [] | [bigint],
  'kannada' : [] | [bigint],
  'appliedMaths' : [] | [bigint],
  'english' : [] | [bigint],
  'statistics' : [] | [bigint],
  'science' : [] | [bigint],
}
export type Time = bigint;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'addAcademicEntry' : ActorMethod<
    [bigint, Array<SaveAcademicInput>, [] | [bigint]],
    Array<AcademicEntry>
  >,
  'addCodingChallenge' : ActorMethod<
    [string, string, string, string],
    CodingChallenge
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'calculateCombinedPercentages' : ActorMethod<[], CombinedPercentages>,
  'calculateWeightedPercentages' : ActorMethod<
    [],
    GradeAggregatesWithWeighting
  >,
  'getAcademicEntries' : ActorMethod<[], Array<AcademicEntry>>,
  'getAcademicEntriesByGrade' : ActorMethod<[bigint], Array<AcademicEntry>>,
  'getAcademicEntriesByGradeAndTerm' : ActorMethod<
    [bigint, bigint],
    Array<AcademicEntry>
  >,
  'getAllCodingChallenges' : ActorMethod<[], Array<CodingChallenge>>,
  'getAllGradePercentages' : ActorMethod<[], AllGradesPercentages>,
  'getBoardExamResults' : ActorMethod<[], BoardExamResults>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCodingAttempts' : ActorMethod<[], Array<CodingAttempt>>,
  'getCodingChallenge' : ActorMethod<[bigint], CodingChallenge>,
  'getCombinedAcademicEntriesByGrade' : ActorMethod<
    [bigint],
    {
      'term1' : [] | [AcademicEntry],
      'term2' : [] | [AcademicEntry],
      'combinedTotal' : bigint,
      'combinedAverage' : bigint,
    }
  >,
  'getGradeAggregatePercentages' : ActorMethod<[], GradeAggregates>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'importData' : ActorMethod<[ExportTypes], undefined>,
  'initializeAccessControl' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'retrieveDataExportRequest' : ActorMethod<[string], ExportTypes>,
  'saveBoardExamResults' : ActorMethod<[bigint, bigint], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCodingAttempt' : ActorMethod<
    [bigint, string, string, [] | [bigint]],
    CodingAttempt
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];