/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    name: string;
}
export interface SubjectScores {
    ai?: bigint;
    pe?: bigint;
    evs?: bigint;
    biology?: bigint;
    social?: bigint;
    hindi?: bigint;
    math?: bigint;
    businessStudies?: bigint;
    computer?: bigint;
    economics?: bigint;
    chemistry?: bigint;
    accountancy?: bigint;
    physics?: bigint;
    management?: bigint;
    psychology?: bigint;
    kannada?: bigint;
    english?: bigint;
    statistics?: bigint;
    science?: bigint;
}
export type Time = bigint;
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface AcademicEntriesExport {
    academicEntries: Array<[Principal, Array<AcademicEntry>]>;
    boardExamResults: Array<[Principal, BoardExamResults]>;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface AcademicEntry {
    totalFinalMarks: bigint;
    stream?: string;
    subjects: SubjectScores;
    term: bigint;
    gradeText: string;
    overallPercentage: bigint;
    subgroup?: string;
    maxMarksPerSubject: bigint;
    overallMaxMarks: bigint;
    grade: bigint;
    termMaxMarks: bigint;
    subjects9?: Score9Scale;
    timestamp: Time;
    termPercentage: bigint;
    computerMaxMarks: bigint;
    termTotalMarks: bigint;
    aiMaxMarks: bigint;
}
export interface BoardExamResults {
    maxMarks: bigint;
    boardExamTotal: bigint;
    percentage: bigint;
}
export interface Score9Scale {
    ai?: number;
    pe?: number;
    evs?: number;
    biology?: number;
    social?: number;
    hindi?: number;
    math?: number;
    businessStudies?: number;
    computer?: number;
    economics?: number;
    chemistry?: number;
    accountancy?: number;
    physics?: number;
    management?: number;
    psychology?: number;
    kannada?: number;
    english?: number;
    statistics?: number;
    science?: number;
}
export interface SaveAcademicInput {
    marks: SubjectScores;
    stream?: string;
    term: bigint;
    subgroup?: string;
    termMaxMarks: bigint;
    marks9?: Score9Scale;
    computerMaxMarks: bigint;
    aiMaxMarks: bigint;
}
export interface ExportTypes {
    academicEntries: AcademicEntriesExport;
    coding: CodingExport;
}
export interface GradeAggregate {
    term2Percentage: bigint;
    combinedOverallPercentage: bigint;
    term1Percentage: bigint;
}
export interface CodingAttempt {
    result: string;
    code: string;
    score?: bigint;
    challengeId: bigint;
    timestamp: Time;
}
export interface CodingExport {
    attempts: Array<[Principal, Array<CodingAttempt>]>;
    challenges: Array<CodingChallenge>;
}
export interface GradeAggregates {
    aggregates: Array<[bigint, GradeAggregate]>;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface CodingChallenge {
    id: bigint;
    title: string;
    sampleOutput: string;
    description: string;
    sampleInput: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    addAcademicEntry(grade: bigint, academicInputs: Array<SaveAcademicInput>, _finalMarks: bigint | null): Promise<Array<AcademicEntry>>;
    addCodingChallenge(title: string, description: string, sampleInput: string, sampleOutput: string): Promise<CodingChallenge>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAcademicEntries(): Promise<Array<AcademicEntry>>;
    getAcademicEntriesByGrade(grade: bigint): Promise<Array<AcademicEntry>>;
    getAcademicEntriesByGradeAndTerm(grade: bigint, term: bigint): Promise<Array<AcademicEntry>>;
    getAllCodingChallenges(): Promise<Array<CodingChallenge>>;
    getBoardExamResults(): Promise<BoardExamResults>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCodingAttempts(): Promise<Array<CodingAttempt>>;
    getCodingChallenge(id: bigint): Promise<CodingChallenge>;
    getCombinedAcademicEntriesByGrade(grade: bigint): Promise<{
        term1?: AcademicEntry;
        term2?: AcademicEntry;
        combinedTotal: bigint;
        combinedAverage: bigint;
    }>;
    getGradeAggregatePercentages(): Promise<GradeAggregates>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    importData(data: ExportTypes): Promise<void>;
    initializeAccessControl(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    retrieveDataExportRequest(exportType: string): Promise<ExportTypes>;
    saveBoardExamResults(boardExamTotal: bigint, maxMarks: bigint): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCodingAttempt(challengeId: bigint, code: string, result: string, score: bigint | null): Promise<CodingAttempt>;
}
import type { AcademicEntriesExport as _AcademicEntriesExport, AcademicEntry as _AcademicEntry, BoardExamResults as _BoardExamResults, CodingAttempt as _CodingAttempt, CodingChallenge as _CodingChallenge, CodingExport as _CodingExport, ExportTypes as _ExportTypes, SaveAcademicInput as _SaveAcademicInput, Score9Scale as _Score9Scale, SubjectScores as _SubjectScores, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async addAcademicEntry(arg0: bigint, arg1: Array<SaveAcademicInput>, arg2: bigint | null): Promise<Array<AcademicEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.addAcademicEntry(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAcademicEntry(arg0, to_candid_vec_n8(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n15(this._uploadFile, this._downloadFile, arg2));
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async addCodingChallenge(arg0: string, arg1: string, arg2: string, arg3: string): Promise<CodingChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.addCodingChallenge(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addCodingChallenge(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n26(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAcademicEntries(): Promise<Array<AcademicEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicEntries();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicEntries();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAcademicEntriesByGrade(arg0: bigint): Promise<Array<AcademicEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicEntriesByGrade(arg0);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicEntriesByGrade(arg0);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAcademicEntriesByGradeAndTerm(arg0: bigint, arg1: bigint): Promise<Array<AcademicEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAcademicEntriesByGradeAndTerm(arg0, arg1);
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAcademicEntriesByGradeAndTerm(arg0, arg1);
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCodingChallenges(): Promise<Array<CodingChallenge>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCodingChallenges();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCodingChallenges();
            return result;
        }
    }
    async getBoardExamResults(): Promise<BoardExamResults> {
        if (this.processError) {
            try {
                const result = await this.actor.getBoardExamResults();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBoardExamResults();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCodingAttempts(): Promise<Array<CodingAttempt>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodingAttempts();
                return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodingAttempts();
            return from_candid_vec_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCodingChallenge(arg0: bigint): Promise<CodingChallenge> {
        if (this.processError) {
            try {
                const result = await this.actor.getCodingChallenge(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCodingChallenge(arg0);
            return result;
        }
    }
    async getCombinedAcademicEntriesByGrade(arg0: bigint): Promise<{
        term1?: AcademicEntry;
        term2?: AcademicEntry;
        combinedTotal: bigint;
        combinedAverage: bigint;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getCombinedAcademicEntriesByGrade(arg0);
                return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCombinedAcademicEntriesByGrade(arg0);
            return from_candid_record_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getGradeAggregatePercentages(): Promise<GradeAggregates> {
        if (this.processError) {
            try {
                const result = await this.actor.getGradeAggregatePercentages();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGradeAggregatePercentages();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async importData(arg0: ExportTypes): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.importData(to_candid_ExportTypes_n36(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.importData(to_candid_ExportTypes_n36(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initializeAccessControl();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async retrieveDataExportRequest(arg0: string): Promise<ExportTypes> {
        if (this.processError) {
            try {
                const result = await this.actor.retrieveDataExportRequest(arg0);
                return from_candid_ExportTypes_n52(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.retrieveDataExportRequest(arg0);
            return from_candid_ExportTypes_n52(this._uploadFile, this._downloadFile, result);
        }
    }
    async saveBoardExamResults(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveBoardExamResults(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveBoardExamResults(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCodingAttempt(arg0: bigint, arg1: string, arg2: string, arg3: bigint | null): Promise<CodingAttempt> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCodingAttempt(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
                return from_candid_CodingAttempt_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCodingAttempt(arg0, arg1, arg2, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg3));
            return from_candid_CodingAttempt_n32(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_AcademicEntriesExport_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicEntriesExport): AcademicEntriesExport {
    return from_candid_record_n55(_uploadFile, _downloadFile, value);
}
function from_candid_AcademicEntry_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AcademicEntry): AcademicEntry {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_CodingAttempt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CodingAttempt): CodingAttempt {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_CodingExport_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CodingExport): CodingExport {
    return from_candid_record_n59(_uploadFile, _downloadFile, value);
}
function from_candid_ExportTypes_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExportTypes): ExportTypes {
    return from_candid_record_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Score9Scale_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Score9Scale): Score9Scale {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_SubjectScores_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubjectScores): SubjectScores {
    return from_candid_record_n21(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Score9Scale]): Score9Scale | null {
    return value.length === 0 ? null : from_candid_Score9Scale_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [number]): number | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AcademicEntry]): AcademicEntry | null {
    return value.length === 0 ? null : from_candid_AcademicEntry_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFinalMarks: bigint;
    stream: [] | [string];
    subjects: _SubjectScores;
    term: bigint;
    gradeText: string;
    overallPercentage: bigint;
    subgroup: [] | [string];
    maxMarksPerSubject: bigint;
    overallMaxMarks: bigint;
    grade: bigint;
    termMaxMarks: bigint;
    subjects9: [] | [_Score9Scale];
    timestamp: _Time;
    termPercentage: bigint;
    computerMaxMarks: bigint;
    termTotalMarks: bigint;
    aiMaxMarks: bigint;
}): {
    totalFinalMarks: bigint;
    stream?: string;
    subjects: SubjectScores;
    term: bigint;
    gradeText: string;
    overallPercentage: bigint;
    subgroup?: string;
    maxMarksPerSubject: bigint;
    overallMaxMarks: bigint;
    grade: bigint;
    termMaxMarks: bigint;
    subjects9?: Score9Scale;
    timestamp: Time;
    termPercentage: bigint;
    computerMaxMarks: bigint;
    termTotalMarks: bigint;
    aiMaxMarks: bigint;
} {
    return {
        totalFinalMarks: value.totalFinalMarks,
        stream: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.stream)),
        subjects: from_candid_SubjectScores_n20(_uploadFile, _downloadFile, value.subjects),
        term: value.term,
        gradeText: value.gradeText,
        overallPercentage: value.overallPercentage,
        subgroup: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.subgroup)),
        maxMarksPerSubject: value.maxMarksPerSubject,
        overallMaxMarks: value.overallMaxMarks,
        grade: value.grade,
        termMaxMarks: value.termMaxMarks,
        subjects9: record_opt_to_undefined(from_candid_opt_n22(_uploadFile, _downloadFile, value.subjects9)),
        timestamp: value.timestamp,
        termPercentage: value.termPercentage,
        computerMaxMarks: value.computerMaxMarks,
        termTotalMarks: value.termTotalMarks,
        aiMaxMarks: value.aiMaxMarks
    };
}
function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: [] | [bigint];
    pe: [] | [bigint];
    evs: [] | [bigint];
    biology: [] | [bigint];
    social: [] | [bigint];
    hindi: [] | [bigint];
    math: [] | [bigint];
    businessStudies: [] | [bigint];
    computer: [] | [bigint];
    economics: [] | [bigint];
    chemistry: [] | [bigint];
    accountancy: [] | [bigint];
    physics: [] | [bigint];
    management: [] | [bigint];
    psychology: [] | [bigint];
    kannada: [] | [bigint];
    english: [] | [bigint];
    statistics: [] | [bigint];
    science: [] | [bigint];
}): {
    ai?: bigint;
    pe?: bigint;
    evs?: bigint;
    biology?: bigint;
    social?: bigint;
    hindi?: bigint;
    math?: bigint;
    businessStudies?: bigint;
    computer?: bigint;
    economics?: bigint;
    chemistry?: bigint;
    accountancy?: bigint;
    physics?: bigint;
    management?: bigint;
    psychology?: bigint;
    kannada?: bigint;
    english?: bigint;
    statistics?: bigint;
    science?: bigint;
} {
    return {
        ai: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.ai)),
        pe: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.pe)),
        evs: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.evs)),
        biology: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.biology)),
        social: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.social)),
        hindi: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.hindi)),
        math: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.math)),
        businessStudies: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.businessStudies)),
        computer: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.computer)),
        economics: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.economics)),
        chemistry: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.chemistry)),
        accountancy: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.accountancy)),
        physics: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.physics)),
        management: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.management)),
        psychology: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.psychology)),
        kannada: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.kannada)),
        english: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.english)),
        statistics: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.statistics)),
        science: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.science))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai: [] | [number];
    pe: [] | [number];
    evs: [] | [number];
    biology: [] | [number];
    social: [] | [number];
    hindi: [] | [number];
    math: [] | [number];
    businessStudies: [] | [number];
    computer: [] | [number];
    economics: [] | [number];
    chemistry: [] | [number];
    accountancy: [] | [number];
    physics: [] | [number];
    management: [] | [number];
    psychology: [] | [number];
    kannada: [] | [number];
    english: [] | [number];
    statistics: [] | [number];
    science: [] | [number];
}): {
    ai?: number;
    pe?: number;
    evs?: number;
    biology?: number;
    social?: number;
    hindi?: number;
    math?: number;
    businessStudies?: number;
    computer?: number;
    economics?: number;
    chemistry?: number;
    accountancy?: number;
    physics?: number;
    management?: number;
    psychology?: number;
    kannada?: number;
    english?: number;
    statistics?: number;
    science?: number;
} {
    return {
        ai: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.ai)),
        pe: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.pe)),
        evs: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.evs)),
        biology: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.biology)),
        social: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.social)),
        hindi: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.hindi)),
        math: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.math)),
        businessStudies: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.businessStudies)),
        computer: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.computer)),
        economics: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.economics)),
        chemistry: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.chemistry)),
        accountancy: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.accountancy)),
        physics: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.physics)),
        management: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.management)),
        psychology: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.psychology)),
        kannada: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.kannada)),
        english: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.english)),
        statistics: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.statistics)),
        science: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.science))
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: string;
    code: string;
    score: [] | [bigint];
    challengeId: bigint;
    timestamp: _Time;
}): {
    result: string;
    code: string;
    score?: bigint;
    challengeId: bigint;
    timestamp: Time;
} {
    return {
        result: value.result,
        code: value.code,
        score: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.score)),
        challengeId: value.challengeId,
        timestamp: value.timestamp
    };
}
function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    term1: [] | [_AcademicEntry];
    term2: [] | [_AcademicEntry];
    combinedTotal: bigint;
    combinedAverage: bigint;
}): {
    term1?: AcademicEntry;
    term2?: AcademicEntry;
    combinedTotal: bigint;
    combinedAverage: bigint;
} {
    return {
        term1: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.term1)),
        term2: record_opt_to_undefined(from_candid_opt_n35(_uploadFile, _downloadFile, value.term2)),
        combinedTotal: value.combinedTotal,
        combinedAverage: value.combinedAverage
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicEntries: _AcademicEntriesExport;
    coding: _CodingExport;
}): {
    academicEntries: AcademicEntriesExport;
    coding: CodingExport;
} {
    return {
        academicEntries: from_candid_AcademicEntriesExport_n54(_uploadFile, _downloadFile, value.academicEntries),
        coding: from_candid_CodingExport_n58(_uploadFile, _downloadFile, value.coding)
    };
}
function from_candid_record_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicEntries: Array<[Principal, Array<_AcademicEntry>]>;
    boardExamResults: Array<[Principal, _BoardExamResults]>;
}): {
    academicEntries: Array<[Principal, Array<AcademicEntry>]>;
    boardExamResults: Array<[Principal, BoardExamResults]>;
} {
    return {
        academicEntries: from_candid_vec_n56(_uploadFile, _downloadFile, value.academicEntries),
        boardExamResults: value.boardExamResults
    };
}
function from_candid_record_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attempts: Array<[Principal, Array<_CodingAttempt>]>;
    challenges: Array<_CodingChallenge>;
}): {
    attempts: Array<[Principal, Array<CodingAttempt>]>;
    challenges: Array<CodingChallenge>;
} {
    return {
        attempts: from_candid_vec_n60(_uploadFile, _downloadFile, value.attempts),
        challenges: value.challenges
    };
}
function from_candid_tuple_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_AcademicEntry>]): [Principal, Array<AcademicEntry>] {
    return [
        value[0],
        from_candid_vec_n16(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_tuple_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<_CodingAttempt>]): [Principal, Array<CodingAttempt>] {
    return [
        value[0],
        from_candid_vec_n31(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AcademicEntry>): Array<AcademicEntry> {
    return value.map((x)=>from_candid_AcademicEntry_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CodingAttempt>): Array<CodingAttempt> {
    return value.map((x)=>from_candid_CodingAttempt_n32(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_AcademicEntry>]>): Array<[Principal, Array<AcademicEntry>]> {
    return value.map((x)=>from_candid_tuple_n57(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<_CodingAttempt>]>): Array<[Principal, Array<CodingAttempt>]> {
    return value.map((x)=>from_candid_tuple_n61(_uploadFile, _downloadFile, x));
}
function to_candid_AcademicEntriesExport_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicEntriesExport): _AcademicEntriesExport {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_AcademicEntry_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AcademicEntry): _AcademicEntry {
    return to_candid_record_n44(_uploadFile, _downloadFile, value);
}
function to_candid_CodingAttempt_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CodingAttempt): _CodingAttempt {
    return to_candid_record_n51(_uploadFile, _downloadFile, value);
}
function to_candid_CodingExport_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CodingExport): _CodingExport {
    return to_candid_record_n46(_uploadFile, _downloadFile, value);
}
function to_candid_ExportTypes_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExportTypes): _ExportTypes {
    return to_candid_record_n37(_uploadFile, _downloadFile, value);
}
function to_candid_SaveAcademicInput_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SaveAcademicInput): _SaveAcademicInput {
    return to_candid_record_n10(_uploadFile, _downloadFile, value);
}
function to_candid_Score9Scale_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Score9Scale): _Score9Scale {
    return to_candid_record_n14(_uploadFile, _downloadFile, value);
}
function to_candid_SubjectScores_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SubjectScores): _SubjectScores {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    marks: SubjectScores;
    stream?: string;
    term: bigint;
    subgroup?: string;
    termMaxMarks: bigint;
    marks9?: Score9Scale;
    computerMaxMarks: bigint;
    aiMaxMarks: bigint;
}): {
    marks: _SubjectScores;
    stream: [] | [string];
    term: bigint;
    subgroup: [] | [string];
    termMaxMarks: bigint;
    marks9: [] | [_Score9Scale];
    computerMaxMarks: bigint;
    aiMaxMarks: bigint;
} {
    return {
        marks: to_candid_SubjectScores_n11(_uploadFile, _downloadFile, value.marks),
        stream: value.stream ? candid_some(value.stream) : candid_none(),
        term: value.term,
        subgroup: value.subgroup ? candid_some(value.subgroup) : candid_none(),
        termMaxMarks: value.termMaxMarks,
        marks9: value.marks9 ? candid_some(to_candid_Score9Scale_n13(_uploadFile, _downloadFile, value.marks9)) : candid_none(),
        computerMaxMarks: value.computerMaxMarks,
        aiMaxMarks: value.aiMaxMarks
    };
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai?: bigint;
    pe?: bigint;
    evs?: bigint;
    biology?: bigint;
    social?: bigint;
    hindi?: bigint;
    math?: bigint;
    businessStudies?: bigint;
    computer?: bigint;
    economics?: bigint;
    chemistry?: bigint;
    accountancy?: bigint;
    physics?: bigint;
    management?: bigint;
    psychology?: bigint;
    kannada?: bigint;
    english?: bigint;
    statistics?: bigint;
    science?: bigint;
}): {
    ai: [] | [bigint];
    pe: [] | [bigint];
    evs: [] | [bigint];
    biology: [] | [bigint];
    social: [] | [bigint];
    hindi: [] | [bigint];
    math: [] | [bigint];
    businessStudies: [] | [bigint];
    computer: [] | [bigint];
    economics: [] | [bigint];
    chemistry: [] | [bigint];
    accountancy: [] | [bigint];
    physics: [] | [bigint];
    management: [] | [bigint];
    psychology: [] | [bigint];
    kannada: [] | [bigint];
    english: [] | [bigint];
    statistics: [] | [bigint];
    science: [] | [bigint];
} {
    return {
        ai: value.ai ? candid_some(value.ai) : candid_none(),
        pe: value.pe ? candid_some(value.pe) : candid_none(),
        evs: value.evs ? candid_some(value.evs) : candid_none(),
        biology: value.biology ? candid_some(value.biology) : candid_none(),
        social: value.social ? candid_some(value.social) : candid_none(),
        hindi: value.hindi ? candid_some(value.hindi) : candid_none(),
        math: value.math ? candid_some(value.math) : candid_none(),
        businessStudies: value.businessStudies ? candid_some(value.businessStudies) : candid_none(),
        computer: value.computer ? candid_some(value.computer) : candid_none(),
        economics: value.economics ? candid_some(value.economics) : candid_none(),
        chemistry: value.chemistry ? candid_some(value.chemistry) : candid_none(),
        accountancy: value.accountancy ? candid_some(value.accountancy) : candid_none(),
        physics: value.physics ? candid_some(value.physics) : candid_none(),
        management: value.management ? candid_some(value.management) : candid_none(),
        psychology: value.psychology ? candid_some(value.psychology) : candid_none(),
        kannada: value.kannada ? candid_some(value.kannada) : candid_none(),
        english: value.english ? candid_some(value.english) : candid_none(),
        statistics: value.statistics ? candid_some(value.statistics) : candid_none(),
        science: value.science ? candid_some(value.science) : candid_none()
    };
}
function to_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ai?: number;
    pe?: number;
    evs?: number;
    biology?: number;
    social?: number;
    hindi?: number;
    math?: number;
    businessStudies?: number;
    computer?: number;
    economics?: number;
    chemistry?: number;
    accountancy?: number;
    physics?: number;
    management?: number;
    psychology?: number;
    kannada?: number;
    english?: number;
    statistics?: number;
    science?: number;
}): {
    ai: [] | [number];
    pe: [] | [number];
    evs: [] | [number];
    biology: [] | [number];
    social: [] | [number];
    hindi: [] | [number];
    math: [] | [number];
    businessStudies: [] | [number];
    computer: [] | [number];
    economics: [] | [number];
    chemistry: [] | [number];
    accountancy: [] | [number];
    physics: [] | [number];
    management: [] | [number];
    psychology: [] | [number];
    kannada: [] | [number];
    english: [] | [number];
    statistics: [] | [number];
    science: [] | [number];
} {
    return {
        ai: value.ai ? candid_some(value.ai) : candid_none(),
        pe: value.pe ? candid_some(value.pe) : candid_none(),
        evs: value.evs ? candid_some(value.evs) : candid_none(),
        biology: value.biology ? candid_some(value.biology) : candid_none(),
        social: value.social ? candid_some(value.social) : candid_none(),
        hindi: value.hindi ? candid_some(value.hindi) : candid_none(),
        math: value.math ? candid_some(value.math) : candid_none(),
        businessStudies: value.businessStudies ? candid_some(value.businessStudies) : candid_none(),
        computer: value.computer ? candid_some(value.computer) : candid_none(),
        economics: value.economics ? candid_some(value.economics) : candid_none(),
        chemistry: value.chemistry ? candid_some(value.chemistry) : candid_none(),
        accountancy: value.accountancy ? candid_some(value.accountancy) : candid_none(),
        physics: value.physics ? candid_some(value.physics) : candid_none(),
        management: value.management ? candid_some(value.management) : candid_none(),
        psychology: value.psychology ? candid_some(value.psychology) : candid_none(),
        kannada: value.kannada ? candid_some(value.kannada) : candid_none(),
        english: value.english ? candid_some(value.english) : candid_none(),
        statistics: value.statistics ? candid_some(value.statistics) : candid_none(),
        science: value.science ? candid_some(value.science) : candid_none()
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicEntries: AcademicEntriesExport;
    coding: CodingExport;
}): {
    academicEntries: _AcademicEntriesExport;
    coding: _CodingExport;
} {
    return {
        academicEntries: to_candid_AcademicEntriesExport_n38(_uploadFile, _downloadFile, value.academicEntries),
        coding: to_candid_CodingExport_n45(_uploadFile, _downloadFile, value.coding)
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    academicEntries: Array<[Principal, Array<AcademicEntry>]>;
    boardExamResults: Array<[Principal, BoardExamResults]>;
}): {
    academicEntries: Array<[Principal, Array<_AcademicEntry>]>;
    boardExamResults: Array<[Principal, _BoardExamResults]>;
} {
    return {
        academicEntries: to_candid_vec_n40(_uploadFile, _downloadFile, value.academicEntries),
        boardExamResults: value.boardExamResults
    };
}
function to_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    totalFinalMarks: bigint;
    stream?: string;
    subjects: SubjectScores;
    term: bigint;
    gradeText: string;
    overallPercentage: bigint;
    subgroup?: string;
    maxMarksPerSubject: bigint;
    overallMaxMarks: bigint;
    grade: bigint;
    termMaxMarks: bigint;
    subjects9?: Score9Scale;
    timestamp: Time;
    termPercentage: bigint;
    computerMaxMarks: bigint;
    termTotalMarks: bigint;
    aiMaxMarks: bigint;
}): {
    totalFinalMarks: bigint;
    stream: [] | [string];
    subjects: _SubjectScores;
    term: bigint;
    gradeText: string;
    overallPercentage: bigint;
    subgroup: [] | [string];
    maxMarksPerSubject: bigint;
    overallMaxMarks: bigint;
    grade: bigint;
    termMaxMarks: bigint;
    subjects9: [] | [_Score9Scale];
    timestamp: _Time;
    termPercentage: bigint;
    computerMaxMarks: bigint;
    termTotalMarks: bigint;
    aiMaxMarks: bigint;
} {
    return {
        totalFinalMarks: value.totalFinalMarks,
        stream: value.stream ? candid_some(value.stream) : candid_none(),
        subjects: to_candid_SubjectScores_n11(_uploadFile, _downloadFile, value.subjects),
        term: value.term,
        gradeText: value.gradeText,
        overallPercentage: value.overallPercentage,
        subgroup: value.subgroup ? candid_some(value.subgroup) : candid_none(),
        maxMarksPerSubject: value.maxMarksPerSubject,
        overallMaxMarks: value.overallMaxMarks,
        grade: value.grade,
        termMaxMarks: value.termMaxMarks,
        subjects9: value.subjects9 ? candid_some(to_candid_Score9Scale_n13(_uploadFile, _downloadFile, value.subjects9)) : candid_none(),
        timestamp: value.timestamp,
        termPercentage: value.termPercentage,
        computerMaxMarks: value.computerMaxMarks,
        termTotalMarks: value.termTotalMarks,
        aiMaxMarks: value.aiMaxMarks
    };
}
function to_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    attempts: Array<[Principal, Array<CodingAttempt>]>;
    challenges: Array<CodingChallenge>;
}): {
    attempts: Array<[Principal, Array<_CodingAttempt>]>;
    challenges: Array<_CodingChallenge>;
} {
    return {
        attempts: to_candid_vec_n47(_uploadFile, _downloadFile, value.attempts),
        challenges: value.challenges
    };
}
function to_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    result: string;
    code: string;
    score?: bigint;
    challengeId: bigint;
    timestamp: Time;
}): {
    result: string;
    code: string;
    score: [] | [bigint];
    challengeId: bigint;
    timestamp: _Time;
} {
    return {
        result: value.result,
        code: value.code,
        score: value.score ? candid_some(value.score) : candid_none(),
        challengeId: value.challengeId,
        timestamp: value.timestamp
    };
}
function to_candid_tuple_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<AcademicEntry>]): [Principal, Array<_AcademicEntry>] {
    return [
        value[0],
        to_candid_vec_n42(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_tuple_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, Array<CodingAttempt>]): [Principal, Array<_CodingAttempt>] {
    return [
        value[0],
        to_candid_vec_n49(_uploadFile, _downloadFile, value[1])
    ];
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_vec_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<AcademicEntry>]>): Array<[Principal, Array<_AcademicEntry>]> {
    return value.map((x)=>to_candid_tuple_n41(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AcademicEntry>): Array<_AcademicEntry> {
    return value.map((x)=>to_candid_AcademicEntry_n43(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, Array<CodingAttempt>]>): Array<[Principal, Array<_CodingAttempt>]> {
    return value.map((x)=>to_candid_tuple_n48(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CodingAttempt>): Array<_CodingAttempt> {
    return value.map((x)=>to_candid_CodingAttempt_n50(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<SaveAcademicInput>): Array<_SaveAcademicInput> {
    return value.map((x)=>to_candid_SaveAcademicInput_n9(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
